module.exports = [
	{edge: 10, skills: ['as']},
	{edge: 10, skills: ['scythe']},
	{edge: 9, skills: ['as']},
	{edge: 9, skills: ['cs', 'tc', 'roll', 'scythe']},
	{edge: 9, skills: ['chargingslash', 'roll', 'scythe']},
	{edge: 9, skills: ['tob', 'roll', 'scythe']},
	{edge: 9, skills: ['rf', 'roll', 'scythe']},
	{edge: 9, skills: ['scythe']},
	{edge: 8, skills: ['as']},
	{edge: 8, skills: ['pb', 'scythe']},
	{edge: 8, skills: ['cs', 'rob', 'scythe']},
	{edge: 8, skills: ['cs', 'rs', 'roll', 'scythe']},
	{edge: 7, skills: ['cs', 'as']},
	{edge: 7, skills: ['chargingslash', 'as']},
	{edge: 7, skills: ['tob', 'as']},
	{edge: 7, skills: ['rs', 'as']},
	{edge: 7, skills: ['rf', 'as']},
	{edge: 7, skills: ['bw', 'bd']},
	{edge: 7, skills: ['chargingslash', 'bd']},
	{edge: 7, skills: ['cs', 'tc', 'bd']},
	{edge: 7, skills: ['rf', 'bd']},
	{edge: 7, skills: ['pb']},
	{edge: 7, skills: ['cs', 'rob']},
	{edge: 7, skills: ['dfa']},
	{edge: 7, skills: ['bs']},
	
	{edge: null, skills: ['bw', 'bd']},
	{edge: null, skills: ['chargingslash', 'bd']},
	{edge: null, skills: ['cs', 'tc', 'bd']},
	{edge: null, skills: ['rf', 'bd']},
	{edge: null, skills: ['pb']},
	{edge: null, skills: ['cs', 'rob']},
	{edge: null, skills: ['dfa']},
	{edge: null, skills: ['bs']},
];
